/* global SERVICE_URL, RETRIEVER_COLLECTION_NAME, BOOKING_COLLECTION_NAME, CONFIRMATION_COLLECTION_NAME */
const config = {
  SERVICE_URL: SERVICE_URL,
  RETRIEVER_COLLECTION_NAME: RETRIEVER_COLLECTION_NAME,
  BOOKING_COLLECTION_NAME: BOOKING_COLLECTION_NAME,
  CONFIRMATION_COLLECTION_NAME: CONFIRMATION_COLLECTION_NAME
};
export default config;
